name: websocket_tester
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  audioplayers: ^0.19.1
  bloc: ^7.0.0
  cupertino_icons: ^1.0.2
  draggable_scrollbar: ^0.1.0
  easy_localization: ^3.0.0
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^7.1.0
  flutter_highlight: ^0.7.0
  flutter_html: ^2.0.0
  flutter_secure_storage: ^4.2.1
  formz: ^0.4.0
  google_fonts: ^2.1.0
  http: ^0.13.3
  path_provider: ^2.0.2
  restart_app: ^1.0.3
  settings_ui: ^1.0.0
  shared_preferences: ^2.0.6
  sizer: ^2.0.13
  sqflite: ^2.0.0+3
  sqflite_common_ffi: ^2.0.0+1
  sqlite3: ^1.1.2
  sqlite3_library_windows: ^2.1.0
  string_validator: ^0.3.0
  syntax_highlighter: ^0.1.1
  tabbed_view: ^1.1.1
  theme_provider: ^0.5.0
  web_socket_channel: ^2.1.0

dev_dependencies:
  flutter_launcher_icons: "^0.9.1"
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/settings.png
    # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Righteous
      fonts:
        - asset: assets/fonts/Righteous-Regular.ttf

          weight: 700
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
